<?php

/**
 * @file
 * Contains example_user_register.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function example_user_register_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the example_user_register module.
    case 'help.page.example_user_register':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Example user register') . '</p>';
      return $output;

    default:
  }
}
